name: interrogation
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  firebase_core_platform_interface: 4.5.2
  firebase_core: ^2.1.0
  firebase_auth: ^4.0.2
  crypt: ^4.2.1
  google_fonts: ^4.0.1
  cloud_firestore: ^4.0.2
  provider: ^6.0.4
  table_calendar: ^3.0.9
  image_picker: ^0.8.6
  font_awesome_flutter: ^10.2.1
  dropdown_search: ^5.0.3
  photo_view: ^0.14.0
  speech_to_text: ^6.1.0
  flutter_tts: ^3.5.3
  crypto: ^3.0.2
  whatsapp: ^2.0.0
  firebase_storage: ^11.0.6
  path: ^1.8.2
  twilio_flutter: ^0.0.9
  connectivity_plus: ^3.0.2
  intl: ^0.18.0



  http: ^0.13.5
  
  
  
  cron: ^0.5.0
  pdf: ^3.8.3
  path_provider: ^2.0.11
  open_file_plus: ^3.3.0
  mailer: ^6.0.0
  
  


  
  


  
  cupertino_icons: ^1.0.5
  firebase_core_dart: ^1.0.1
  flutter_launcher_icons: ^0.11.0



  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.jpeg"


flutter:

  uses-material-design: true
  assets:
     - images/
     - assets/database.db
 
